from __future__ import annotations

import importlib
from typing import Any

_MODULES = {
    "AcDbFace": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Basics.ac_db_face",
    "AcDb3dSolid": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.2D3D Modeling.ac_db_3d_solid",
    "AcDbBody": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.2D3D Modeling.ac_db_body",
    "AcDbRegion": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.2D3D Modeling.ac_db_region",
    "AcDbSubDMesh": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.2D3D Modeling.ac_db_sub_dmesh",
    "AcDbBlockReference": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Basics.ac_db_block_reference",
    "AcDbCamera": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Basics.ac_db_camera",
    "AcDbFrame": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Basics.ac_db_frame",
    "AcDbHatch": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Basics.ac_db_hatch",
    "AcDbImage": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Basics.ac_db_image",
    "AcDbLight": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Basics.ac_db_light",
    "AcDbMLeader": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Basics.ac_db_mleader",
    "AcDbMline": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Basics.ac_db_mline",
    "AcDbMText": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Basics.ac_db_mtext",
    "AcDbPoint": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Basics.ac_db_point",
    "AcDbPointCloud": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Basics.ac_db_point_cloud",
    "AcDbPointCloudEx": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Basics.ac_db_point_cloud_ex",
    "AcDbPolyFaceMesh": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Basics.ac_db_poly_face_mesh",
    "AcDbPolygonMesh": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Basics.ac_db_polygon_mesh",
    "AcDbProxyEntity": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Basics.ac_db_proxy_entity",
    "AcDbSection": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Basics.ac_db_section",
    "AcDbShape": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Basics.ac_db_shape",
    "AcDbSolid": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Basics.ac_db_solid",
    "AcDbText": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Basics.ac_db_text",
    "AcDbViewport": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Basics.ac_db_viewport",
    "AcDbMInsertBlock": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Basics.AcDbBlockReference.ac_db_minsert_block",
    "AcDbTable": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Basics.AcDbBlockReference.ac_db_table",
    "AcDbViewRepBlockReference": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Basics.AcDbBlockReference.ac_db_view_rep_block_reference",
    "AcDbOleFrame": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Basics.AcDbFrame.ac_db_ole_frame",
    "AcDbOle2Frame": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Basics.AcDbFrame.AcDbOleFrame.ac_db_ole2_frame",
    "AcDbRasterImage": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Basics.AcDbImage.ac_db_raster_image",
    "AcDbGeoMap": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Basics.AcDbImage.AcDbRasterImage.ac_db_geo_map",
    "AcDbWipeout": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Basics.AcDbImage.AcDbRasterImage.ac_db_wipeout",
    "AcDbAttribute": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Basics.AcDbText.ac_db_attribute",
    "AcDbAttributeDefinition": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Basics.AcDbText.ac_db_attribute_definition",
    "AcDbBlockBegin": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Bracket Entities.ac_db_block_begin",
    "AcDbBlockEnd": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Bracket Entities.ac_db_block_end",
    "AcDbSequenceEnd": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Bracket Entities.ac_db_sequence_end",
    "AcDbCurve": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Curves.ac_db_curve",
    "AcDb2dPolyline": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Curves.AcDbCurve.ac_db_2d_polyline",
    "AcDb3dPolyline": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Curves.AcDbCurve.ac_db_3d_polyline",
    "AcDbArc": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Curves.AcDbCurve.ac_db_arc",
    "AcDbCircle": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Curves.AcDbCurve.ac_db_circle",
    "AcDbEllipse": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Curves.AcDbCurve.ac_db_ellipse",
    "AcDbLeader": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Curves.AcDbCurve.ac_db_leader",
    "AcDbLine": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Curves.AcDbCurve.ac_db_line",
    "AcDbPolyline": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Curves.AcDbCurve.ac_db_polyline",
    "AcDbSpline": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Curves.AcDbCurve.ac_db_spline",
    "AcDbXline": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Curves.AcDbCurve.ac_db_xline",
    "AcDbHelix": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Curves.AcDbCurve.AcDbSpline.ac_db_helix",
    "AcDbDimension": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Dimensions.ac_db_dimension",
    "AcDb3PointAngularDimension": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Dimensions.AcDbDimension.ac_db_3point_angular_dimension",
    "AcDbAlignedDimension": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Dimensions.AcDbDimension.ac_db_aligned_dimension",
    "AcDbAngularDimension": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Dimensions.AcDbDimension.ac_db_angular_dimension",
    "AcDbArcDimension": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Dimensions.AcDbDimension.ac_db_arc_dimension",
    "AcDbDiametricDimension": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Dimensions.AcDbDimension.ac_db_diametric_dimension",
    "AcDbFcf": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Dimensions.AcDbDimension.ac_db_feature_control_frame",
    "AcDbOrdinateDimension": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Dimensions.AcDbDimension.ac_db_ordinate_dimension",
    "AcDbRadialDimension": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Dimensions.AcDbDimension.ac_db_radial_dimension",
    "AcDbRotatedDimension": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Dimensions.AcDbDimension.ac_db_rotated_dimension",
    "AcDbRadialDimensionLarge": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Dimensions.AcDbDimension.AcDbRadialDimension.ac_db_radial_dimension_large",
    "AcDbViewBorder": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Model Documentation.ac_db_view_border",
    "AcDbViewSymbol": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Model Documentation.ac_db_view_symbol",
    "AcDbSurface": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Surfaces.ac_db_surface",
    "AcDbExtrudedSurface": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Surfaces.AcDbSurface.ac_db_extruded_surface",
    "AcDbNurbSurface": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Surfaces.AcDbSurface.ac_db_nurb_surface",
    "AcDbPlaneSurface": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Surfaces.AcDbSurface.ac_db_plane_surface",
    "AcDbRevolvedSurface": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Surfaces.AcDbSurface.ac_db_revolved_surface",
    "AcDbSweptSurface": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Surfaces.AcDbSurface.ac_db_swept_surface",
    "AcDbUnderlayReference": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Underlays.ac_db_underlay_reference",
    "AcDbVertex": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Vertex Subentities.ac_db_vertex",
    "AcDb2dVertex": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Vertex Subentities.AcDbVertex.ac_db_2d_vertex",
    "AcDb3dPolylineVertex": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Vertex Subentities.AcDbVertex.ac_db_3d_polyline_vertex",
    "AcDbFaceRecord": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Vertex Subentities.AcDbVertex.ac_db_face_record",
    "AcDbPolyFaceMeshVertex": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Vertex Subentities.AcDbVertex.ac_db_poly_face_mesh_vertex",
    "AcDbPolygonMeshVertex": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Entities.AcDbEntity.Vertex Subentities.AcDbVertex.ac_db_polygon_mesh_vertex",
    "AcDbDataTable": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Miscellaneous.ac_db_data_table",
    "AcDbDictionary": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Miscellaneous.ac_db_dictionary",
    "AcDbDictionaryEntry": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Miscellaneous.ac_db_dictionary",
    "AcDbDictionaryWithDefault": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Miscellaneous.ac_db_dictionary",
    "AcDbGroup": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Miscellaneous.ac_db_group",
    "AcDbLinkedData": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Miscellaneous.ac_db_linked_data",
    "AcDbMaterial": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Miscellaneous.ac_db_material",
    "AcDbMLeaderStyle": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Miscellaneous.ac_db_mleader_style",
    "AcDbMlineStyle": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Miscellaneous.ac_db_mline_style",
    "AcDbPlotSettings": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Miscellaneous.ac_db_plot_settings",
    "AcDbLayout": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Miscellaneous.AcDbPlotSettings.ac_db_layout",
    "AcDbTableStyle": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Miscellaneous.ac_db_table_style",
    "AcDbXrecord": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Miscellaneous.ac_db_xrecord",
    "AcDbSymbolTableRecord": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Symbol Table Records.ac_db_symbol_table_record",
    "AcDbBlockTableRecord": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Symbol Table Records.AcDbSymbolTableRecord.ac_db_block_table_record",
    "AcDbDimStyleTableRecord": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Symbol Table Records.AcDbSymbolTableRecord.ac_db_dim_style_table_record",
    "AcDbLayerTableRecord": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Symbol Table Records.AcDbSymbolTableRecord.ac_db_layer_table_record",
    "AcDbLinetypeTableRecord": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Symbol Table Records.AcDbSymbolTableRecord.ac_db_linetype_table_record",
    "AcDbRegAppTableRecord": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Symbol Table Records.AcDbSymbolTableRecord.ac_db_reg_app_table_record",
    "AcDbTextStyleTableRecord": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Symbol Table Records.AcDbSymbolTableRecord.ac_db_text_style_table_record",
    "AcDbUcsTableRecord": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Symbol Table Records.AcDbSymbolTableRecord.ac_db_ucs_table_record",
    "AcDbAbstractViewTableRecord": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Symbol Table Records.AcDbSymbolTableRecord.ac_db_view_table_record",
    "AcDbViewTableRecord": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Symbol Table Records.AcDbSymbolTableRecord.ac_db_view_table_record",
    "AcDbViewportTableRecord": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Symbol Table Records.AcDbSymbolTableRecord.ac_db_view_table_record",
    "AcDbSymbolTable": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Symbol Tables.ac_db_symbol_table",
    "AcDbBlockTable": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Symbol Tables.AcDbSymbolTable.ac_db_block_table",
    "AcDbDimStyleTable": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Symbol Tables.AcDbSymbolTable.ac_db_dim_style_table",
    "AcDbLayerTable": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Symbol Tables.AcDbSymbolTable.ac_db_layer_table",
    "AcDbLinetypeTable": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Symbol Tables.AcDbSymbolTable.ac_db_linetype_table",
    "AcDbRegAppTable": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Symbol Tables.AcDbSymbolTable.ac_db_reg_app_table",
    "AcDbTextStyleTable": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Symbol Tables.AcDbSymbolTable.ac_db_text_style_table",
    "AcDbUcsTable": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Symbol Tables.AcDbSymbolTable.ac_db_ucs_table",
    "AcDbAbstractViewTable": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Symbol Tables.AcDbSymbolTable.ac_db_view_table",
    "AcDbViewTable": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Symbol Tables.AcDbSymbolTable.ac_db_view_table",
    "AcDbViewportTable": "server.dwg.dwg_model.AcRxObject.Database Objects.AcDbObject.Symbol Tables.AcDbSymbolTable.ac_db_view_table",
}


def __getattr__(name: str) -> Any:
    if name in _MODULES:
        value = getattr(importlib.import_module(_MODULES[name]), name)
        globals()[name] = value
        return value
    raise AttributeError(name)


__all__ = sorted(_MODULES)
